### ISSUE TITLE
Not able to install in windows wsl

### ISSUE THREAD

**Issue by cpjoshi** [codecrafters-io/docs#20]
Path: /cli/installation?_gl=1*v7x3m4*_ga*MTQxNDk1MTA5LjE3MTAxNjg1MTM.*_ga_N8D6K4M2HE*MTcxMDU2NDYzNC4zLjAuMTcxMDU2NDYzNC4wLjAuMA..

______________________________________
````
~$ curl -k https://codecrafters.io/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1990  100  1990    0     0  10900      0 --:--:-- --:--:-- --:--:-- 10874
This script will automatically install codecrafters (v23) for you.
You will be prompted for your password by sudo if needed.
Installation path: /usr/local/bin/codecrafters
Downloading CodeCrafters CLI...
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
````

**Comment by rohitpaulk** [comment]
Hey @cpjoshi! This seems like a issue with your connection to github. The "Downloading CodeCrafters CLI..." step actually contacts GitHub. Can you try running this within that same terminal session and share the output you get? 

```
curl -vvv https://github.com
```

Here's the line where it downlads the release: https://github.com/codecrafters-io/cli/blob/4acf567d788f2a814943ad3128a2507b80fe1c59/install.sh#L36C15-L36C71

I'm going to close this until we have a confirmed bug + reproduction step, but feel free to respond and re-open when you've got more details!
