### ISSUE TITLE
codecrafters test can't work: find repository root folder: add all files: Unknown option: -C

### ISSUE THREAD

**Issue by Garbage123King** [codecrafters-io/docs#25]
Path: /cli/usage
[root@node01 codecrafters-sqlite-python]# codecrafters test
find repository root folder: add all files: Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

[root@node01 codecrafters-sqlite-python]# ls
app               download_sample_databases.sh  Pipfile.lock  sample.db
codecrafters.yml  Pipfile                       README.md     your_sqlite3.sh
[root@node01 codecrafters-sqlite-python]#

**Comment by rohitpaulk** [comment]
Hey @Garbage123King! Thanks for reporting this. 

What OS are you on? And what does `git --version` give you?

**Comment by rohitpaulk** [comment]
Closing since we haven't received a response in a while, please re-open if you're still facing issues!
