### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by joss12** [codecrafters-io/docs#43]
Path: /challenges/debug-test-failures

Hey, I'm currently facing this issue when debugging 

[build] Build failed. Check the logs above for the reason.
[build] If you think this is a CodeCrafters error, please contact us at hello@codecrafters.io.

**Comment by rohitpaulk** [comment]
@joss12 mind sharing the logs above those lines? Hard to tell what's wrong without more information.

**Comment by rohitpaulk** [comment]
Closing for now, please post on https://forum.codecrafters.io/ if you still need help!
