### ISSUE TITLE
Images in the "How do I debug test failures" page not showing

### ISSUE THREAD

**Issue by lmmendes** [codecrafters-io/docs#56]
Path: /challenges/debug-test-failures [link to page](https://docs.codecrafters.io/challenges/debug-test-failures)

Both images  `debug-mode-off-code.png` and `debug-mode-on-code.png` are not showing in the documentation.

> <img width="748" alt="Screenshot 2024-09-08 at 15 45 09" src="https://github.com/user-attachments/assets/f0278da5-054c-49dc-af16-912b48f0869d">

When trying to open the image in a new tab I get the following error from the aws s3 bucket:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>YDWMT93S3NG1D9KQ</RequestId>
<HostId>
2OKy9q2TNd1Kf08PefHMC+cQ8JSawZlHsd7gHIslB+YiaxreyW7xgy9wvt/8q0YfPd0ur/1ch2Q=
</HostId>
</Error>
```

**Comment by lmmendes** [comment]
Unfortunately ended up figuring out that the issue was with my "ad blocker" (ublock origin).

Closing the issue since everything is working as expected, sorry for the inconvenience.

**Comment by rohitpaulk** [comment]
@lmmendes this was actually a bug! I fixed it just now by triggering a redeploy 🙂 Found out from here: https://x.com/IsaacHarrisHolt/status/1832501248358298033
